apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  labels:
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:8 # ถ้าต้องการเวอร์ชัน 8 เปลี่ยนเป็น gotenberg/gotenberg:8
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: CHROMIUM_DISABLE_ROUTES
              value: "false"
            - name: CHROMIUM_IGNORE_CERTIFICATE_ERRORS
              value: "true"
            - name: CHROMIUM_ALLOW_LIST
              value: ".*"
            - name: TZ
              value: "Asia/Bangkok" # เพิ่ม Time Zone ที่นี่
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg-service
spec:
  selector:
    app: gotenberg
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
